- name: Install required packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - "openjdk-8-jdk"
      - "python3"
      - "acl"
      - "rsync"
